### ISSUE TITLE
Possible some improvements

### ISSUE THREAD

**Issue by eos1d3** [BetaBen1/A-Guide-to-MacOS-Scaled-Resolutions#3]
Why not using https://github.com/headkaze/Hackintool instead which shows Vendor ID and Product ID using Displays tab. The way of searching the IDs are too time consuming.

When using RDM, it shows every scale resolutions for me. I am confused the need for adding display plist for extra resolutions. All are already there.

Big Sur does not allow to add plists inside /System/Library. The write enable command does not work any more. Instead, copying display plist to exact same path to /Library works too.

**Comment by bbhardin** [comment]
Thanks for the comments. I was able to use Hackintool to help me get this working in Big Sur. I will add these improvements to the guide. Would you like me to cite your GitHub handle in the guide for suggesting using this tool?

**Comment by eos1d3** [comment]
No need to cite me. Just help all others is good enough.

**Comment by bbhardin** [comment]
Sounds great. Thanks!
