### ISSUE TITLE
Probably no longer possible to mount partition as writable

### ISSUE THREAD

**Issue by ghost** [BetaBen1/A-Guide-to-MacOS-Scaled-Resolutions#4]
https://superuser.com/questions/1681655/how-to-change-a-read-only-file-system-to-a-writable-file-system-on-mac-monterey

**Comment by bbhardin** [comment]
Thanks for flagging this. You are correct that mounting the partition as writable is no longer possible (at least not without some serious hacking). Luckily, there is a workaround, and I will update the guide soon with this information. :)

**Comment by JonnyTech** [comment]
Please can you update us @bbhardin?
